Repository lucy-kim04/4-ViewMyStartup-team1-FE, pull requests merged in 2024-12, with the labels that each got.

#4 chore: 필요한 디렉토리 추가
  src/assets/.gitkeep
  src/components/.gitkeep
  src/db/.gitkeep
  src/hooks/.gitkeep
  src/utils/.gitkeep
Labels: chore

#15 BREAKING: 프론트엔드 최종 세팅
  src/apis/getStartups.js
  src/apis/hyeongmin.js
  src/apis/kim
  src/apis/kirinnim.js
Labels: BREAKING

#16 BREAKING: 프론트엔드 세팅 최종(진짜)
  src/App.js
  src/apis/getCompanies.js
  src/apis/kem
  src/pages/CompanyListPage.js
  src/pages/CompanyPage.js
  src/pages/StartupPage.js
Labels: BREAKING

#18 [조형민 - Feature/17] MyComarisionPage UI 및 기능 구현 완료
  .eslintrc.cjs
  .prettierrc.js
  public/favicon.ico
  public/index.html
  src/App.js
  src/assets/images/ic_check.png
  src/assets/images/ic_delete.png
  src/assets/images/ic_delete_circle_small.png
  src/assets/images/ic_minus.png
  src/assets/images/ic_plus.png
  src/assets/images/ic_search.png
  src/assets/images/vms_logo_2x.png
  src/components/.gitkeep
  src/components/CompanyListWidget.css
  src/components/CompanyListWidget.js
  src/components/CompanyWidget.css
  src/components/CompanyWidget.js
  src/components/ComparisionCompanyWidget.css
  src/components/ComparisionCompanyWidget.js
  src/components/Container.css
  src/components/Container.js
  src/components/HeaderJHM.css
  src/components/HearderJHM.js
  src/components/SelectComparisionCompanyModal.css
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.css
  src/components/SelectMyCompanyModal.js
  src/db/mock.js
  src/index.css
  src/index.js
  src/lib/axios.js
  src/pages/CompanyListPage.js
  src/pages/MyComparisionPage.css
  src/pages/MyComparisionPage.js
  src/utils/setCategoryEngToKor.js
Labels: feat

#24 [조형민] MyComparisionPage 구현 완료 #23
  src/apis/getComapniesModal.js
  src/apis/getCompanies.js
  src/apis/getLatestSelections.js
  src/apis/updateCompany.js
  src/apis/updateUser.js
  src/assets/images/ic_restart.png
  src/components/CompanyListWidget.css
  src/components/CompanyListWidget.js
  src/components/Container.css
  src/components/SelectComparisionCompanyModal.css
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.js
  src/index.css
  src/lib/axios.js
  src/pages/MyComparisionPage.css
  src/pages/MyComparisionPage.js
Labels: feat

#26 [조형민] 에러 팝업 모달 구현 완료 #25
  src/components/AlertModal.js
  src/components/SelectComparisionCompanyModal.css
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.css
  src/components/SelectMyCompanyModal.js
Labels: feat

#27 hotfix: 나의 기업 선택 모달창의 배경 높이가 전체로 설정되지 않는 버그 수정
  src/components/SelectMyCompanyModal.css
Labels: fix

#29 [조형민] ‘기업 비교’ 구현 완료 - Feature/28
  src/apis/getCompanyRank.js
  src/assets/images/btn_visibility_off_24px.png
  src/assets/images/btn_visibility_on_24px.png
  src/assets/images/ic_arrow_left.png
  src/assets/images/ic_arrow_right.png
  src/assets/images/ic_toggle.png
  src/components/AlertModal.css
  src/components/AlertModal.js
  src/components/CompanyTableRank.css
  src/components/CompanyTableRank.js
  src/components/CompanyTableResult.css
  src/components/CompanyTableResult.js
  src/components/CompanyWidgetHor.css
  src/components/CompanytWidgetHor.js
  src/components/CompareCompanyBox.css
  src/components/CompareCompanyBox.js
  src/components/Container.css
  src/components/HeaderJHM.css
  src/components/HearderJHM.js
  src/components/MyCompanyBox.css
  src/components/MyCompanyBox.js
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.css
  src/components/SelectMyCompanyModal.js
  src/index.css
  src/pages/MyComparisionPage.css
  src/pages/MyComparisionPage.js
  src/pages/MyComparisionResultPage.css
  src/pages/MyComparisionResultPage.js
Labels: feat

#30 hotfix: getCompanyRank API 리턴 항목에서 myCompanyIdx삭제 #28
  src/pages/MyComparisionResultPage.js
Labels: fix

#31 hotfix: 비교 기업 추가 모달에 '취소'버튼 추가
  src/components/SelectComparisionCompanyModal.css
  src/components/SelectComparisionCompanyModal.js
  src/index.css
Labels: fix

#32 feat: 기업소개 text overflow 구현
  src/components/CompanyTableRank.css
  src/components/CompanyTableRank.js
  src/components/CompanyTableResult.css
  src/components/CompanyTableResult.js
Labels: fix

#33 [조형민] API 파일명 및 함수명 변경 외 Fix
  src/apis/getComapniesModal_jhm.js
  src/apis/getCompanies_jhm.js
  src/apis/getCompanyRank_jhm.js
  src/apis/getLatestSelections.js
  src/apis/getLatestSelections_jhm.js
  src/apis/updateCompany.js
  src/apis/updateCompany_jhm.js
  src/apis/updateUser.js
  src/apis/updateUser_jhm.js
  src/components/CompanyTableRank.css
  src/components/CompanyTableRank.js
  src/components/CompanyTableResult.css
  src/components/CompanyTableResult.js
  src/components/CompanyWidget.css
  src/components/CompanyWidgetHor.css
  src/components/ComparisionCompanyWidget.css
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.js
  src/pages/MyComparisionPage.js
  src/pages/MyComparisionResultPage.js
Labels: fix, chore

#35 feat: 비교 결과 테이블에 정렬 기능 추가 #34
  src/components/CompanyTableRank.js
  src/components/CompanyTableResult.js
  src/pages/MyComparisionResultPage.js
Labels: feat

#36 fix: 헤더 아래에 underline 추가
  src/index.css
  src/pages/MyComparisionPage.css
  src/pages/MyComparisionPage.js
  src/pages/MyComparisionResultPage.css
  src/pages/MyComparisionResultPage.js
Labels: feat

#37 feat: 버튼 및 헤더 메뉴 롤오버 정리
  src/components/HeaderJHM.css
  src/index.css
Labels: fix

#39 feat: 오류 처리 코드 추가, 마이너 버그 수정
  src/apis/getComapniesModal_jhm.js
  src/apis/getCompanies_jhm.js
  src/apis/getCompanyRank_jhm.js
  src/apis/getLatestSelections_jhm.js
  src/apis/updateCompany_jhm.js
  src/apis/updateUser_jhm.js
  src/components/AlertModal.css
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.js
  src/pages/MyComparisionPage.js
  src/pages/MyComparisionResultPage.js
Labels: feat, fix

#40 feat: 페이지네이션(공통 모듈) 연동
  src/components/HeaderKSH.js
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.js
Labels: feat

#41 [구은모] feat: CompanyListPage 구현중 #20
  src/components/CompanyList.css
  src/components/CompanyList.js
  src/components/HeaderKEM.css
  src/components/HeaderKEM.js
  src/components/StartupTableHead.css
  src/components/StartupTableHead.js
  src/components/TitleAndSaerch.css
  src/components/TitleAndSearch.js
  src/db/mockKem.js
  src/pages/CompanyListPage.css
  src/pages/CompanyListPage.js
Labels: feat, build

#42 feat: Company detail UI #21
  src/components/CompanyDetailInfo.css
  src/components/CompanyDetailInfo.js
  src/components/CompanyInvestmentSection.css
  src/components/CompanyInvestmentSection.js
  src/components/HeaderKJY.css
  src/components/HeaderKJY.js
  src/db/companyMock.js
  src/pages/CompanyPage.css
  src/pages/CompanyPage.js
Labels: feat

#43 fix: 주영님 머지 후 이것저것 fix
  src/components/CompanyDetailInfo.css
  src/components/CompanyDetailInfo.js
  src/components/HeaderKEM.js
  src/pages/CompanyPage.css
  src/pages/InvestmentStatusPage.js
Labels: fix

#45 feat: 기업 상세 페이지에 location추가(with 주영님)
  src/components/CompanyInvestmentSection.js
  src/pages/CompanyPage.js
Labels: feat, fix

#48 feat: '비교 결과 확인하기', '기업 순위 확인하기' 드롭다운 메뉴로 정렬 구현
  src/components/CompanyTableRank.css
  src/components/CompanyTableRank.js
  src/components/CompanyTableResult.css
  src/components/CompanyTableResult.js
  src/pages/MyComparisionResultPage.js
Labels: feat

#53 [김세환] InvestmentStatusPage orderBy mapping 수정 및 InvestmentList rank 수정 #52
  src/apis/getInvestments.js
  src/components/InvestmentList.css
  src/components/InvestmentList.js
  src/components/Pagination.css
  src/components/Pagination.js
  src/pages/InvestmentStatusPage.css
  src/pages/InvestmentStatusPage.js
  src/test.test
Labels: chore, refactor

#56 fix: eslint etc
  .eslintrc.cjs
  .prettierrc.js
  src/components/CompanyTableResult.js
  src/components/SelectMyCompanyModal.js
Labels: fix

#57 fix: eslint 폭파
  . prettierignore
  .eslintrc.cjs
  .gitignore
  .prettierrc.js
  package-lock.json
  package.json
  src/components/HearderJHM.js
Labels: fix
