Repository lucy-kim04/4-ViewMyStartup-team1-FE, pull requests merged in 2025-01, with the labels that each got.

#63 refactor: 강의용 파일 정리 등
  src/apis/getCompany_kjy.js
  src/components/CompanyDetailInfo.js
  src/components/Container.css
  src/components/Dropdown.js
  src/components/HearderJHM.js
  src/components/Pagination.js
  src/components/SelectComparisionCompanyModal.js
  src/components/SelectMyCompanyModal.js
  src/pages/CompanyListPage.js
  src/pages/CompanyPage.js
  src/pages/MyComparisionPage.css
  src/pages/MyComparisionPage.js
  src/pages/MyComparisionResultPage.css
  src/pages/MyComparisionResultPage.js
  src/utils/convertNumTo100M.js
  src/utils/setCategoryEngToKor.js
Labels: refactor

#60 [김희주] feat: 비교현황 헤더 UI 구현
  src/components/HeaderKHJ.css
  src/components/HeaderKHJ.js
  src/pages/ComparisionStatusPage.js
  src/pages/ComparisonStatusPage.css
Labels: feat

#70 [김세환] Pagination itemsPerPage 원복 및 buttonSize prop 추가 #69
  src/components/CompanyInvestmentModal.css
  src/components/CompanyInvestmentModal.js
  src/components/HeaderKSH.js
  src/components/Pagination.css
  src/components/Pagination.js
  src/pages/InvestmentStatusPage.js
Labels: feat, fix

#72 fix: Pagination.css 복구
  src/components/Pagination.css
  src/components/my-comparison/SelectMyCompanyModal.js
Labels: fix

#73 feat: '나의기업비교', '기업비교결과' 페이지 반응형 구현 완료
  src/components/AlertModal.css
  src/components/AlertModal.js
  src/components/my-comparison/CompanyTableRank.css
  src/components/my-comparison/CompanyTableResult.css
  src/components/my-comparison/CompanyWidget.css
  src/components/my-comparison/CompanyWidgetHor.css
  src/components/my-comparison/CompareCompanyBox.css
  src/components/my-comparison/ComparisionCompanyWidget.css
  src/components/my-comparison/SelectComparisionCompanyModal.css
  src/components/my-comparison/SelectComparisionCompanyModal.js
  src/components/my-comparison/SelectMyCompanyModal.css
  src/components/my-comparison/SelectMyCompanyModal.js
  src/index.css
  src/pages/MyComparisionPage.js
Labels: feat

#76 [구은모] BE연결 및 UI구현
  src/apis/getCompanies_KEM.js
  src/components/CompanyList.css
  src/components/CompanyList.js
  src/components/StartupTableHead.css
  src/components/StartupTableHead.js
  src/components/TitleAndSaerch.css
  src/components/TitleAndSearch.js
  src/db/mockKem.js
  src/pages/CompanyListPage.css
  src/pages/CompanyListPage.js
  src/utils/convertNumTo100M.js
Labels: feat

#77 feat: 기업 상세 페이지 기능 구현
  src/apis/getCompanyInvestments.js
  src/components/CompanyDetailInfo.js
  src/components/CompanyInvestmentSection.css
  src/components/CompanyInvestmentSection.js
  src/components/my-comparison/CompanyTableRank.css
  src/components/my-comparison/CompanyTableRank.js
  src/components/my-comparison/CompanyTableResult.css
  src/components/my-comparison/CompanyTableResult.js
  src/components/my-comparison/MyCompanyBox.js
  src/pages/CompanyPage.js
  src/pages/MyComparisionPage.js
Labels: feat

#83 [김세환] CompanyInvestmentModal UI 및 기능 구현 #81
  src/components/CompanyInvestmentModal.css
  src/components/CompanyInvestmentModal.js
  src/components/InvestmentSuccessModal.css
  src/components/InvestmentSuccessModal.js
Labels: feat

#84 feat: InvestmentDeleteModal UI 구현
  src/apis/deleteInvestment_ksh.js
  src/apis/postInvestment_ksh.js
  src/components/InvestmentDeleteModal.css
  src/components/InvestmentDeleteModal.js
  src/pages/InvestmentStatusPage.js
Labels: feat

#80 [김주영 ]fix: company detail page #79
  src/components/CompanyDetailInfo.css
  src/components/CompanyDetailInfo.js
  src/components/CompanyInvestmentSection.css
  src/components/CompanyInvestmentSection.js
  src/pages/CompanyPage.js
Labels: feat, fix

#87 [구은모] 랭킹 및 상단 UI정리 #78
  src/components/CompanyList.css
  src/components/CompanyList.js
  src/components/HeaderKEM.js
  src/components/TitleAndSaerch.css
  src/components/TitleAndSearch.js
Labels: feat, chore

#90 [조형민] feat: 비교 현황 페이지 데이터 연결 및 정렬 구현 완료
  src/apis/getCompanies_khj.js
  src/components/SelectionCount.js
  src/pages/ComparisionStatusPage.js
  src/pages/ComparisonStatusPage.css
Labels: feat

#91 fix: company detail page #88
  src/components/CompanyDetailInfo.css
  src/components/CompanyInvestmentSection.css
  src/components/CompanyInvestmentSection.js
  src/pages/CompanyPage.css
  src/pages/CompanyPage.js
Labels: fix

#94 [조형민] 기업 상세 페이지 '투자목록'의 메뉴 버튼 동작 수정
  src/components/CompanyInvestmentModal.js
  src/components/CompanyInvestmentSection.js
  src/pages/MyComparisionResultPage.js
Labels: fix

#95 [구은모] feat: search기능 구현 및 테이블 및 search UI 수정 #89
  src/components/CompanyList.css
  src/components/CompanyList.js
  src/components/StartupTableHead.css
  src/components/TitleAndSaerch.css
  src/components/TitleAndSearch.js
Labels: feat, chore

#98 [구은모] feat:Pagination,Dropdown 컴포넌트 적용 #97
  src/components/CompanyList.js
  src/components/TitleAndSaerch.css
  src/components/TitleAndSearch.js
Labels: feat

#99 [조형민] 기업상세 페이지의 투자목록 border문제 해결, 기업 상세 이동 링크 추가
  src/components/CompanyInvestmentSection.css
  src/components/CompanyList.js
Labels: feat, fix

#103 [김세환] InvestmentDeleteModal 및 InvestmentDeleteFailModal UI 및 기능 구현 #100
  src/apis/deleteInvestment_ksh.js
  src/apis/getCompanies_ksh.js
  src/apis/getInvestments_ksh.js
  src/components/InvestmentDeleteFailModal.css
  src/components/InvestmentDeleteFailModal.js
  src/components/InvestmentDeleteModal.css
  src/components/InvestmentDeleteModal.js
  src/pages/InvestmentStatusPage.js
Labels: feat

#112 feat: css 수정
  src/components/SelectionCount.css
  src/pages/ComparisonStatusPage.css
Labels: style
